# Usage - docker run -it mitgcm_ad_v2_amd64 /bin/bash -l

FROM --platform=linux/amd64 ubuntu:22.04
LABEL org.opencontainers.image.authors="shreyasg911@gmail.com"

# # Define a user
RUN apt-get update && apt-get -y install sudo
RUN useradd -u 2000 -m test | chpasswd && adduser test sudo

# Add some packages
# Unable to add - which zlib-devel perl-Digest-MD5
RUN apt-get update -y --allow-unauthenticated
RUN apt-get install -y make git
RUN apt-get install -y diffutils vim
RUN apt-get install -y autoconf automake
RUN apt-get install -y valgrind
RUN apt-get install -y build-essential gfortran
RUN apt-get install -y bc wget unzip
RUN apt-get install -y libnetcdf-dev
RUN apt-get install -y libnetcdff-dev
RUN apt-get install -y libhdf5-dev
RUN apt-get install -y default-jre
# RUN apt-get install -y mpich
# RUN apt-get install -y openmpi-devel
# RUN sudo apt-get install openmpi-bin openmpi-common openssh-client openssh-server libopenmpi1.3 libopenmpi-dbg libopenmpi-dev
RUN sudo apt-get install -y openmpi-bin openmpi-common openssh-client openssh-server libopenmpi-dev

# MITgcm
WORKDIR /
RUN git clone https://github.com/MITgcm/MITgcm

# Tapenade
WORKDIR /
RUN wget https://tapenade.gitlabpages.inria.fr/tapenade/distrib/tapenade_3.16.tar
RUN tar xvfz tapenade_3.16.tar
ENV TAPENADE_HOME=/tapenade_3.16
ENV PATH=$PATH:$TAPENADE_HOME/bin

# Python
WORKDIR /
RUN apt-get install -y python3 python3-pip
RUN pip3 install numpy
RUN pip3 install scipy
RUN pip3 install pytest

# Alias python3 as python
RUN echo "alias python=/usr/bin/python3" >> ~/.bash_profile
RUN . ~/.bash_profile