#!/bin/bash

##set terminal
export TERM=xterm-256color

##prompt variables escape sequence
##Helps to see the working directory
PS1='\W\$ '

export nickname='lonestar6'

##Modules
#module use /share/modulefiles/
#module load java/jdk/16.0.1 #Required by Tapenade
module load gcc/11.2.0
module load netcdf/4.7.4
module load cmake/3.24.2
module load cuda
module save

## Directories
export HOME=/home1/07665/shrey911
export WORK=/work/07665/shrey911/ls6
export sha_bash=$HOME/sha_bash
export cuda_course=$WORK/CUDA_course

## Add Julia to path
export PATH="$PATH:$HOME/julia-1.9.1/bin"
export LD_LIBRARY_PATH="$PATH:$HOME/julia-1.9.1/lib"

## set some variables for Tapenade
export JAVA_HOME="/home1/07665/shrey911/jdk-20.0.1"
export PATH="$PATH:$JAVA_HOME/bin:$PATH"

export TAPENADE_HOME="$HOME/tapenade_3.16"
export PATH="$PATH:$TAPENADE_HOME/bin"

# Help find libmpfr.so.6
# A symlink has been created from /usr/lib64/libmpfr.so.4.1.6 to $HOME/libmpfr.so.6
# Seems like a risky hack but whatever
ln -sf /usr/lib64/libmpfr.so.4.1.6 ~/libmpfr.so.6
export LD_LIBRARY_PATH="$HOME:$LD_LIBRARY_PATH"

## set some variables for SICOPOLIS tapenade
export LD_LIBRARY_PATH="$HOME/lis-2.1.3/installation/lib:$LD_LIBRARY_PATH"
## Necessary to find crti* file when using sico.sh
export LIBRARY_PATH=/usr/lib64/:$LIBRARY_PATH

## Environment variables for NetCDF
#export NETCDF_BIN=$TACC_NETCDF_BIN
#export NETCDF_ROOT=$TACC_NETCDF_DIR
#export NETCDF_INC=$TACC_NETCDF_INC
#export NETCDF_LIB=$TACC_NETCDF_LIB
## To find libnetcdff.so.7
## Again something that could be risky
## Note that $HOME is already added to LD_LIBRARY_PATH above
ln -sf /opt/apps/gcc9_4/netcdf/4.6.2/x86_64/lib/libnetcdff.so.6.1.1 ~/libnetcdff.so.7


## Environment variables for CUDA
export CUDA_HOME=$TACC_CUDA_DIR
export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH

## Commands 
alias qu='squeue -u shrey911'
alias ..="cd .."
alias ...="cd ../.."
alias cd..="cd .."
alias julia='LD_LIBRARY_PATH="" julia'
alias gfortran='/opt/apps/gcc/9.4.0/bin/gfortran'

## Increase stack size
ulimit -s hard
ulimit -u hard

### Expand environment variables in tab completion ###
shopt -s direxpand

## group permissions
#umask 027

## Commands for interactive node
alias cuda_interactive='srun -A OCE23001 --partition=gpu-a100 --time=00:30:00 -n1 --pty /bin/bash'
alias interactive='srun -A OCE23001 --partition=normal -t 30 -N 1 --ntasks 4 --cpus-per-task=7 --pty bash -i'

## git authentication
git config --global credential.helper "cache --timeout=86400"

## Other people's directories
# Community portal
export communitydir=/work/projects/aci/ECCO/community

# Patrick
export ph_data=/work/03263/heimbach/data
export ph_work=/work/03263/heimbach/
export ph_scratch=/scratch/03263/heimbach/

# An
export an_work=/work/03901/atnguyen
export an_scratch=/scratch/03901/atnguyen

# Helen
export hp_work=/work/05773/hpillar
export hp_scratch=/scratch/05773/hpillar

# Tim
export ts_work=/work/03754/tsmith
export ts_scratch=/scratch/03754/tsmith

# Joseph
