#!/bin/bash

##set terminal
export TERM=xterm-256color

##prompt variables escape sequence
##Helps to see the working directory
PS1='\W\$ '

##Modules
module load cuda
module save

## Directories
export HOME=/home1/07665/shrey911
export WORK=/work/07665/shrey911/ls6
export sha_bash=$HOME/sha_bash
export cuda_course=$WORK/CUDA_course

## Add Julia to path
export PATH="$PATH:$HOME/julia-1.9.1/bin"
export LD_LIBRARY_PATH="$PATH:$HOME/julia-1.9.1/lib"

##set some variables for Tapenade
export TAPENADE_HOME="$HOME/tapenade_3.16"
export PATH="$PATH:$TAPENADE_HOME/bin"

## Environment variables for CUDA
export CUDA_HOME=$TACC_CUDA_DIR
export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH

## Commands 
alias qu='squeue -u shrey911'
alias ..="cd .."
alias ...="cd ../.."
alias cd..="cd .."
alias julia='LD_LIBRARY_PATH="" julia'

## Increase stack size
ulimit -s hard
ulimit -u hard

### Expand environment variables in tab completion ###
shopt -s direxpand

## group permissions
#umask 027

## Commands for interactive node
alias cuda_interactive='srun -A DPP21001 --partition=gpu-a100 --time=00:30:00 -n1 --pty /bin/bash'
alias interactive='srun -A DPP21001 --partition=normal -t 30 -N 1 --ntasks 4 --cpus-per-task=7 --pty bash -i'

## git authentication
git config --global credential.helper "cache --timeout=86400"

