#!/bin/bash

## Set terminal
export TERM=xterm-256color

## Prompt variables escape sequence
## Helps to see the working directory
PS1='\W\$ '

## Add Julia to path
export PATH="$PATH:/home/shreyas/julia-1.9.1/bin"

## Set some variables for SICOPOLIS tapenade
export TAPENADE_HOME="/home/shreyas/tapenade_3.16"
export PATH="$PATH:$TAPENADE_HOME/bin"
export LD_LIBRARY_PATH="/home/shreyas/lis-2.1.3/installation/lib:$LD_LIBRARY_PATH"
## Necessary to find crti* file when using sico.sh
export LIBRARY_PATH=/usr/lib64/:$LIBRARY_PATH
export LISDIR="/home/shreyas/lis-2.1.3/installation"
export NETCDF_FORTRAN_DIR="/opt/ohpc/pub/libs/gnu/openmpi/netcdf-fortran/4.4.4"

## Modules
module use /share/modulefiles/
module load java/jdk/16.0.1 # Required by Tapenade
module load gnu7/7.3.0
module load openmpi
module load netcdf-fortran
module load netcdf
module load cmake

## Directories
export HOME=/home/shreyas
export SCRATCH=/scratch/shreyas
export sha_bash=~/Miscellaneous/sha_bash
export SSCRATCH=/scratch2/shreyas

## Commands 
alias qu='squeue -u shreyas'
alias cds='cd /scratch/shreyas/'
alias cdss='cd /scratch2/shreyas/'
alias ..="cd .."
alias ...="cd ../.."
alias cd..="cd .."

## Increase stack size
ulimit -s hard
ulimit -u hard

### Expand environment variables in tab completion ###
shopt -s direxpand

## Group permissions
umask 027

## Commands for interactive node and jupyter notebook
alias interactive='srun -t 1440 -N 1 --ntasks 4 --cpus-per-task=7 --pty bash -i'

## git authentication
git config --global credential.helper "cache --timeout=86400"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/scratch2/shreyas/mambaforge/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/scratch2/shreyas/mambaforge/etc/profile.d/conda.sh" ]; then
        . "/scratch2/shreyas/mambaforge/etc/profile.d/conda.sh"
    else
        export PATH="/scratch2/shreyas/mambaforge/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/scratch2/shreyas/mambaforge/etc/profile.d/mamba.sh" ]; then
    . "/scratch2/shreyas/mambaforge/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<

mamba activate py310_LRP

# Source vimrc

source ~/.vimrc

## Other people's directories

# Patrick
export ph_home=/home/heimbach
export ph_scratch=/scratch/heimbach
export ph_scratch2=/scratch2/heimbach

# An
export an_home=/home/atnguyen
export an_scratch=/scratch/atnguyen
export an_scratch2=/scratch2/atnguyen

# Helen
export hp_home=/home/pillarh
export hp_scratch=/scratch/pillarh
export hp_scratch2=/scratch2/pillarh
export hp_matlabdir=$hp_home/HP_MATLAB_SVERDRUP/matlab_forShreyas_adjLRPcompare

# Tim
export ts_home=/home/tsmith
export ts_scratch=/scratch/tsmith
export ts_scratch2=/scratch2/tsmith
